<?xml version="1.0"?>
<package format="3">
  <name>amr_bringup</name>
  <version>0.1.0</version>
  <description>Launch and composition package for the ROS 2 autonomous mobile robot project.</description>
  <maintainer email="tahazarif10@users.noreply.github.com">Taha Zarif</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>amr_description</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>

  <test_depend>launch_testing_ament_cmake</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
