<?xml version="1.0"?>
<package format="3">
  <name>amr_control_adapter</name>
  <version>0.2.0</version>
  <description>Lifecycle-aware ROS 2 adapter around robotics-control-core.</description>
  <maintainer email="tahazarif10@users.noreply.github.com">Taha Zarif</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>diagnostic_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>lifecycle_msgs</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
